name: Muhammad Waleed Profile Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]  # Every 12 hours
  workflow_dispatch:                   # Allow manual runs

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # --- Basic settings ---
          user: mwaleed580
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
          config_ignore_errors: yes

          # --- Visual customization ---
          config_display: large
          config_padding: 0, 12
          config_order: base.header, base.repositories, base.metadata, activity, community
          config_twemoji: yes
          config_animations: yes
          config_octicon: yes

          # --- Plugins ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_skipped: lowlighter/metrics, mwaleed580/Eureka-Booking, mwaleed580/RepliBlocks, mwaleed580/Jobi
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_recent: no
          plugin_languages_colors: github
          plugin_languages_threshold: 0%

          plugin_lines: yes

          plugin_repositories: yes
          plugin_repositories_featured: mwaleed580/Jobi, mwaleed580/Eureka-Booking
          plugin_repositories_order: stars, pushed

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_stargazers: yes
          plugin_stargazers_charts: yes

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_traffic: yes
